Dev
ovrutzki/epicure-project pull request #3
Opened 2023-03-09 12:57 UTC by ovrutzki

2023-03-09 15:00 UTC, ovrutzki commented
היו לי כמה עניינים עם המרג'וג' לדב אז חזרתי commit אחד אחורה
בגרסה הזאת אני לוקח את על המידע לסלייסרים מהmongooDB ועושה לשם הרשמה

2023-03-13 07:54 UTC, YardenTsaraf requested changes
fix and push again

2023-03-13 07:54 UTC, YardenTsaraf commented on front/src/component/LogIn/LogIn.tsx
> +  const [password, setPassword] = useState("");
להוסיף types לשלושת הסטייטים

2023-03-13 07:54 UTC, YardenTsaraf commented on front/src/component/LogIn/LogIn.tsx
> +  const handleLogin = (e: any) => {
לשנות את any

2023-03-13 07:54 UTC, YardenTsaraf commented on front/src/store/slicer/userSlicre.tsx
> +    // builder.addCase(loginUserStore.pending, (state, action) => {
למחוק הערות

2023-03-13 14:56 UTC, YardenTsaraf approved these changes

2023-03-19 06:35 UTC, closed without merging